### ISSUE TITLE
Improve README

### ISSUE THREAD

**Issue by meisterluk** [anexia-it/go-human#17]
Thanks for the software. But how about a better `README` file? How about:

* [x] Current version number
* [x] Current maintainer / author
* [x] Motivation / Problem
* [x] How is the problem solved? Example (Input/Output).
* [x] Who should use it?
* [X] How to install
* [x] How to run the software
* [X] Location of the license
* [x] Location of the source code and issue tracker
* [x] Changelog

**Comment by speijnik** [comment]
Thanks for the report.

Yeah, the README could use some work.

**Comment by md2perpe** [comment]
For the _Motivation / Problem_ part:
The format seems to be similar to basic [YAML](https://en.wikipedia.org/wiki/YAML). How does it differ and what does one gain compared to YAML?

**Comment by speijnik** [comment]
The README was just updated and the initial ChangeLog added to the repository. I addressed some, but not all the problems with the README reported in this issue.

Feedback would be greatly appreciated.

**Comment by meisterluk** [comment]
The ChangeLog hyperlink points to a broken link (upper/lowercasing is wrong).
Besides that, nice work! Much better, thanks! 👍 

I consider all points covered, because you basically address developers only with your package. Hence, "how to install" == "how to run". So, thanks!
